services:
  bng-techspike-integration:
    build:
      context: .
      target: production
    image: bng-techspike-integration
    container_name: bng-techspike-integration
    environment:
      APPINSIGHTS_CLOUDROLE: bng-techspike-integration-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
