services:
  bng-techspike-integration:
    build:
      context: .
      target: production
    image: bng-techspike-integration
    container_name: bng-techspike-integration
    environment:
      APPINSIGHTS_CLOUDROLE: bng-techspike-integration-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      Dynamics365ClientId: ${Dynamics365ClientId}
      Dynamics365ClientSecret: ${Dynamics365ClientSecret}
      Dynamics365AuthorityURL: ${Dynamics365AuthorityURL}
      Dynamics365ServerUrl: ${Dynamics365ServerUrl}
