services:
  bng-techspike-integration:
    build:
      context: .
      target: production
    image: bng-techspike-integration
    container_name: bng-techspike-integration
    environment:
      APPINSIGHTS_CLOUDROLE: bng-techspike-integration-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      Dynamics365ClientId: ${Dynamics365ClientId}
      Dynamics365ClientSecret: ${Dynamics365ClientSecret}
      Dynamics365AuthorityURL: ${Dynamics365AuthorityURL}
      Dynamics365ServerUrl: ${Dynamics365ServerUrl}
      POSTGRES_DB: bng
      POSTGRES_HOST: ${POSTGRES_HOST:-host.docker.internal}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-postgres}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
