{{- include "ffc-helm-library.deployment" (list . "bng-techspike-integration.deployment") -}}
{{- define "bng-techspike-integration.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "bng-techspike-integration.container") }}
{{- end -}}
